version: '2'
services:
  db:
    image: kartoza/postgis:9.6-2.4
    volumes:
      - ~/postgres_data/geoserver:/var/lib/postgresql

  geoserver:
    image: kartoza/geoserver:2.8.0
    volumes:
      - ~/geoserver_data:/opt/geoserver/data_dir
    # ports:
    #   - "8080:8080"
    links:
      - db:db

  s3-sync:
    image: mapseed/geoserver-data-sync:release-1.0.2
    volumes:
      - ~/geoserver_data:/geoserver_data
    environment:
      - USERNAME=${SYNC_USERNAME}
      - PASSWORD=${SYNC_PASSWORD}
      - GEOSERVER_DATA_DIR=${SYNC_GEOSERVER_DATA_DIR}
      - S3_BUCKET=${SYNC_S3_BUCKET}
      - AWS_ACCESS_KEY_ID=${SYNC_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${SYNC_AWS_SECRET_ACCESS_KEY}
    command: sh -c "git stash && git fetch && git checkout master && git pull --rebase && ./start.sh"

  #   volumes:
  #   ports:

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx-envsubst.conf:/etc/nginx/nginx.conf
    links:
      - geoserver
      - s3-sync
    ports:
      - 80:80
    restart: always

